exports.handler = async (event) => {
  const environment = process.env.ENVIRONMENT || "unknown";
  const region      = process.env.AWS_REGION || "unknown";
  const funcName    = process.env.AWS_LAMBDA_FUNCTION_NAME || "unknown";

  // Color theme differs per environment
  const isProd = environment === "prod";
  const accentColor = isProd ? "#e94560" : "#00b4d8";
  const envLabel    = isProd ? "Production" : "Staging";

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${envLabel} — Lambda Static Page</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', sans-serif;
      background: linear-gradient(135deg, #1a1a2e, #16213e, #0f3460);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #fff;
    }
    .card {
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 16px;
      padding: 48px 56px;
      text-align: center;
      max-width: 600px;
      backdrop-filter: blur(10px);
    }
    .badge {
      display: inline-block;
      background: ${accentColor};
      color: #fff;
      font-size: 12px;
      font-weight: 700;
      letter-spacing: 1px;
      text-transform: uppercase;
      padding: 4px 14px;
      border-radius: 20px;
      margin-bottom: 20px;
    }
    h1 { font-size: 2rem; margin-bottom: 12px; }
    p  { color: rgba(255,255,255,0.6); line-height: 1.6; margin-bottom: 24px; }
    .meta {
      background: rgba(0,0,0,0.2);
      border-radius: 10px;
      padding: 16px;
      font-size: 13px;
      color: rgba(255,255,255,0.5);
      text-align: left;
      display: grid;
      gap: 8px;
    }
    .meta span { color: ${accentColor}; font-weight: 600; }
  </style>
</head>
<body>
  <div class="card">
    <div class="badge">${envLabel}</div>
    <h1>Hello from Lambda!</h1>
    <p>This page was generated by a Lambda function exposed via Function URL in the <strong>${envLabel}</strong> environment.</p>
    <div class="meta">
      <div>⏱ <span>Time:</span> ${new Date().toUTCString()}</div>
      <div>🌍 <span>Region:</span> ${region}</div>
      <div>⚙️ <span>Function:</span> ${funcName}</div>
      <div>🏷️ <span>Environment:</span> ${environment}</div>
      <div>📦 <span>Runtime:</span> Node.js ${process.version}</div>
      <div>📦 <span>Git Tag:</span> v1.0.2</div>
    </div>
  </div>
</body>
</html>
  `.trim();

  return {
    statusCode: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
    body: html,
  };
};
